title: Awa Sun Yin's Website
author: awa
subtitle: It takes all the running you can do, to keep in the same place.

url: "https://awasunyin.github.io"
baseurl: ""

footer_only_homepage: true
footer_url: "https://github.com/awasunyin"
footer_text: ""

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Twitter"
   absolute-link: "https://twitter.com/awasunyin"
